### ISSUE TITLE
landing page unresponsive for mobile devices

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [WrippleFoss/mentorFix#117]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Node.js version:
- NPM version
- Operating System:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by abhishek71994** [comment]
Thanks for creating this. I haven't setup the responsiveness for the SASS.
Also all the measurements are to be in relative terms.
Would you like to work on this? @ShreyaPrasad1209

**Comment by ShreyaPrasad1209** [comment]
Yes I'd love to.

**Comment by abhishek71994** [comment]
Perfect. I'll share the figma designs with you later if you need context of it. I need to come up with better style guides. But at the moment, maybe set the styling to `flex` and use `rem` for width and height?

**Comment by abhishek71994** [comment]
Worked and done. Check `./styles` to get more details about the sass mixins.
