### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#196]
The solution to this issue is expected to:
* implement Login design according to Figma
* implement gql to hit the backend API to verify the user logging in, to authenticate and:
  * In case the user is not present, show the corresponding error message.
  * In case the password doesn't match, show the corresponding error message.
  * In case the user is not verified, show the `User not verified` page.
  * In case the user passes the above checks, direct the user further

Use this [link](https://www.figma.com/file/IuUnvGJc0ZqjUsnXF0DtFon3/MentorFix?node-id=21%3A10)
Implement screen 1.3 or 1.2

**Comment by samridhijain27** [comment]
I would like to work on this issue.

**Comment by abhishek71994** [comment]
@samridhijain27 , issue is yours. Contact us if any issue.

**Comment by abhishek71994** [comment]
Update: Get the design as responsive and as close to the design as possible. Not a big blocker.

**Comment by abhishek71994** [comment]
It's been 11 days without a PR @samridhijain27 . Would like an update on how much work is done. If not, someone else can take it up.

**Comment by robot-with-feelings** [comment]
hi, is the issue still open or is someone working on it? if not, i'd like to work on this.

**Comment by abhishek71994** [comment]
@robot-with-feelings you can take it up if you want.

**Comment by robot-with-feelings** [comment]
@abhishek71994 sure. I'd like to implement screen 1.2 using CSS. If that's okay then you can assign me the issue and I'll start working.

**Comment by divyaprakashrx** [comment]
@abhishek71994 I want to work on this issue. I have worked in many front-end works. Please assign it to me.

**Comment by abhishek71994** [comment]
@robot-with-feelings The repo uses modular scss to style things, assigning you the issue, make a PR in 2-3 days and we will take it up from there.

@divyaprakash-Rx There are other issues that are inactive, if it has been inactive for more than 3 days, comment, I'll assign it.

**Comment by robot-with-feelings** [comment]
hi @abhishek71994 just wanted to update you that I'm working on it and will send the PR today itself.

**Comment by NikitaMasand** [comment]
Is this issue open?
If so, I would like to contribute.

**Comment by abhishek71994** [comment]
@robot-with-feelings no PRs were made. Assigning it to @NikitaMasand

**Comment by Ruchika30** [comment]
Hi. If its available I would like to work on it . @abhishek71994

**Comment by NikitaMasand** [comment]
@Ruchika30 I am currently working on it. I had some college work in between. 
@abhishek71994 Will raise the pr in a few hours.
