### ISSUE TITLE
Sign Up screen

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#197]
The current issue is expected to have a solution to:
* Implement the design according to the designs provided.
* Hit the backend using gql to check the following:
    * If the user exists, show the corresponding error message
    * If the user exists and is not verified, show the corresponding error message
    * If the user doesn’t exist:
        * Check for the validity of the email
        * Once these checks are done, upon confirmation from the backend, redirect to the verification screen

Use this [link](https://www.figma.com/file/IuUnvGJc0ZqjUsnXF0DtFon3/MentorFix?node-id=21%3A10)
Implement screen 1.3 or 1.2 and the verify email screen

**Comment by harshita130602** [comment]
I would like to work on it.

**Comment by abhishek71994** [comment]
Go ahead @harshita130602, If you have any questions do check-in via slack.

**Comment by abhishek71994** [comment]
Update: Get the design as responsive and as close to the design as possible. Not a big blocker.

**Comment by abhishek71994** [comment]
It's been 11 days without a PR @harshita130602 . It would be great if you can update how much work is done if any. Else someone else can start on it.

**Comment by harshita130602** [comment]
Sir, I am busy with my exams. I think I won't be able to continue right now. So, you can assign it to someone else.

**Comment by imrishabh18** [comment]
@abhishek71994 assign me this

**Comment by abhishek71994** [comment]
@imrishabh18 assigned to you, please create at least a PR in 3-4 days.

**Comment by divyaprakashrx** [comment]
@abhishek71994 I want to work on this issue.Please assign it to me

**Comment by abhishek71994** [comment]
@imrishabh18 unassigning you. This needs to be done asap

**Comment by divyaprakashrx** [comment]
@abhishek71994 Please check the deign i have implemented.
![Screenshot (98)](https://user-images.githubusercontent.com/55322166/77822116-d4671a00-7115-11ea-8fae-1bd42807df80.png)

**Comment by abhishek71994** [comment]
@divyaprakash-Rx please create a PR, I would like to test it out 💯 . It looks like great work.

**Comment by divyaprakashrx** [comment]
Ok

**Comment by Dishebh** [comment]
@divyaprakash-Rx any updates on the pr?
