### ISSUE TITLE
remove h from mentorFix clone address

### ISSUE THREAD

**Issue by NikitaMasand** [WrippleFoss/mentorFix#200]
git clone hhttps://github.com/WrippleFoss/mentorFix.git
remove h

**Comment by imrishabh18** [comment]
@NikitaMasand Are you resolving this typo or should i do it ?

**Comment by NikitaMasand** [comment]
I am on it

**Comment by abhishek71994** [comment]
Thanks for solving this in #201

**Comment by abhishek71994** [comment]
@imrishabh18 You can take up other issues if you want.
