### ISSUE TITLE
Create a basic Card component

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#206]
![image](https://user-images.githubusercontent.com/8072400/77026787-7cbb0700-69cf-11ea-88da-e275185d311a.png)

Create this basic card component which will render the children inside it.
Check out the link [here](https://www.figma.com/file/IuUnvGJc0ZqjUsnXF0DtFon3/MentorFix?node-id=21%3A10)

**Comment by Samarjiit** [comment]
hi, @abhishek71994 I would like to work on it. actually I am active from today in the slack channel. should I need some prior knowledge? I have to make it in Figma or simple HTML, CSS code.

**Comment by abhishek71994** [comment]
@Samarjiit one has to use the link given to make a react component.

**Comment by Samarjiit** [comment]
I can make a react card component but the link directs me to the Figma platform.

**Comment by sharmakeshav10** [comment]
@abhishek71994 please assign me this issue and further guide me to proceed for the same.

**Comment by Samarjiit** [comment]
hi @sharmakeshav10, actually  i am working on it.

**Comment by abhishek71994** [comment]
Please dont start work before the ticket is assigned to you, this is a `GSSOC20` ticket if you are a participant, ping in the public group and talk to me there.

**Comment by ashishnagpal2498** [comment]
Hi @abhishek71994 can I work on this issue?

**Comment by abhishek71994** [comment]
@ashishnagpal2498 do you have the front-end platform setup?

**Comment by ranjal007** [comment]
Hey! @abhishek71994 I want to contribute in this issue GSSOC 20 . Please assign it to me.

**Comment by abhishek71994** [comment]
@ranjal007 same question for you, do you have the front end setup?

**Comment by ashishnagpal2498** [comment]
Yes @abhishek71994 . I am able to see sign-up and login page.

**Comment by dibakar95** [comment]
@abhishek71994 Can I work on this issue. It has been stale for quite long.

**Comment by abhishek71994** [comment]
@ashishnagpal2498  is working on it @dibakar95 , apologies

**Comment by NikitaMasand** [comment]
Is this issue open? If so, I would like to work on it.

**Comment by abhishek71994** [comment]
Giving it to @dibakar95 for the moment, @NikitaMasand Once you are done with login, if this issue still doesn't have a PR, you can take this up.

**Comment by dibakar95** [comment]
@abhishek71994 thank you.

**Comment by ashishnagpal2498** [comment]
Hi @abhishek71994 , I was working on this issue.

**Comment by abhishek71994** [comment]
@ashishnagpal2498 this is not an issue that should 7 days, neither did you reach out to me on slack to ask or communicate anything. I didn't get a PR from you. Sorry, but I can't have stale issues lying around.

**Comment by ashishnagpal2498** [comment]
okay , no issues. But issue was assigned to me 3 days ago only.

**Comment by Dishebh** [comment]
Is the issue still up for grabs? If yes, can I take it?

**Comment by dibakar95** [comment]
@abhishek71994 At least you could have reviewed the PR

**Comment by abhishek71994** [comment]
Hey @dibakar95 Due to some circumstances, we had to stop all contributions to the project as we are rethinking our approach. Thanks for your PR. Sorry, it couldn't be merged, as the product priorities are re-evaluated at the moment.
