### ISSUE TITLE
Create a nav bar component

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#208]
![image](https://user-images.githubusercontent.com/8072400/77133959-ff12fc00-6a9f-11ea-8182-2743e09a800a.png)

* The navbar component is supposed to change according to the state of login or sign up for the user.
* It should also reflect on the specific roles that each user has.

**Comment by sharmakeshav10** [comment]
@abhishek71994 please assign me this and further guide me to proceed for the same.

**Comment by abhishek71994** [comment]
Try getting a navbar component setup first then make a PR. DM me to set up a call to talk further.

**Comment by abhishek71994** [comment]
@sharmakeshav10 unassigning this issue as there are no PRs nor any communication in the chat.

**Comment by abhushanaj** [comment]
@abhishek71994 May I try this?? I'm a GSSoc participant. Thank you!

**Comment by me-bhavya** [comment]
I am a gssoc 2020 participant and would love to work on this issue. Please assign this to me.

**Comment by dibakar95** [comment]
Hi, @abhishek71994 As I see this issue has been stale since 4-5 days. I am a GSSOC 20 participant. I would like to take up this issue. _Looking forward to your guidance_.

**Comment by aditianshu** [comment]
@abhishek71994 I would like to work on this issue. I have experience working with React. 
GSSoC '20. 
Thanks!

**Comment by abhishek71994** [comment]
Sorry guys, this issue will no longer be a GSSOC issue

**Comment by Kuljeet-123** [comment]
@abhishek71994  I am a GSSOC'20 participant Can I work on this issue??

**Comment by Ruchika30** [comment]
is this done ? If not Can I work on this issue? @abhishek71994 . Please update

**Comment by abhishek71994** [comment]
Go ahead @Ruchika30 , if you have any doubts you can reach out to me on slack or discord
