### ISSUE TITLE
Update PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by Aman-Codes** [WrippleFoss/mentorFix#209]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

This would ease the process of reviewing the pull request by the mentor. I am sharing my created sample template for the same. Do let me know if any changes are needed in it.
![pull request](https://user-images.githubusercontent.com/54680709/77154261-583f5780-6ac1-11ea-945d-5a46c6baf4a9.PNG)

# Current Behavior

No available template for pull request.
@abhishek71994

**Comment by abhishek71994** [comment]
I would like you to include:
## Screenshots (in case of UI changes)

### Issue that this PR solves(Tag the number)

Go ahead with this issue.

**Comment by abhishek71994** [comment]
@Aman-Codes are you contributing as a participant of GSSOC20?

**Comment by Aman-Codes** [comment]
Yes Sir I am a GSSOC 2020 participant

**Comment by dibakar95** [comment]
@abhishek71994 it's been stale for 10 days. Can I take up this issue. #GSSOC2020

**Comment by Dishebh** [comment]
@abhishek71994 is the issue still up for grabs? I see there's a pr for it, bit hasn't been reviewed yet.

**Comment by Dishebh** [comment]
@Aman-Codes Can I take this issue?
