### ISSUE TITLE
Backend : sign-up P1

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#27]
Create a mutation to update the redis server for a temporary post
Generate an email with a magic URL which will, upon visiting, move the user from redis cache to the main mongo DB.(This will be an issue in itself)

Basically the point is to create mutations to make a change in the db/cache and then generate a magic url.

**Comment by abhishek71994** [comment]
@palashg7563 @sweezy793 the next task if either of you are interested please DM me on slack.

**Comment by abhishek71994** [comment]
Dont focus on the description, we have to change that.

**Comment by palashg7563** [comment]
@abhishek71994 @laveesh ohk assign me this one i want to do this

**Comment by palashg7563** [comment]
i am working on this one ;-D

**Comment by abhishek71994** [comment]
@palashg7563 Create another issue to setup
* mongo Connection/schema design
* User(Mentor) Schema
* Using this via graphql

**Comment by sweezy793** [comment]
> @palashg7563 Create issue(s) to setup
> 
> * mongo Connection/schema design
> * User(Mentor) Schema
> * Using this via graphql

@abhishek71994 I would like to work on some of those issues

**Comment by palashg7563** [comment]
@abhishek71994 i think schema design all this stuff will come under this issue as mongodb is different one so i created a different one and and as requested i would like to work on the #49 and #27

**Comment by vipuldcoder** [comment]
I am interested with the issue.
