### ISSUE TITLE
Backend : sign-up P2 (Magic link)

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#28]
Create a magic link for the user to hit (using redis cache probably/mongodb).
Then shift that to the mongoDB (after making certain checks)

Expectations:
* on creation of user(in the redis cache/mongo db), send an email using a background worker.
```{
...userDetails,
verified : false
}
```

* When updated using that link, change the verified field to ``` true ```

_Depending on whether we end up using redis or mongo, do the next process_

**Comment by vipuldcoder** [comment]
I am interested with the issue.
