### ISSUE TITLE
Backend : sign-up P3(Details)

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#29]
## protected url, only verified people will be allowed to use this

This issue comprises of getting all the details necessary for creating a full blown mentor/mentee profile.

Expectations:
* use mutations to update the features related to the user

```
{
username(required)
interests: will be an array of strings/enums(required)
photo: optional feature
location: _if that's of any use_
Bio: A short description(required)
username: github(required),twitter,medium
}
```

**Comment by abhishek71994** [comment]
For mentors,
```
{
...previousData,
skillset:[array of skills strings/enums],
certifications:[{
    cert.name,
    cert.association,
    cert.projects/responsibility //What did the mentor do in the certification
  }]
}
```

**Comment by AvinashDhillor** [comment]
Can i work on this issue?

**Comment by abhishek71994** [comment]
Have you worked with mutations in graphql? as to solve this, you might need to solve P1 and P2 first.
@palashg7563 @sweezy793 collaborate with @AvinashDhillor .

**Comment by sweezy793** [comment]
> Have you worked with mutations in graphql? as to solve this, you might need to solve P1 and P2 first.
> @palashg7563 @sweezy793 collaborate with @AvinashDhillor .

@AvinashDhillor we would need to complete P1 and P2 first, then only we can approach this.

**Comment by palashg7563** [comment]
@sweezy793 first user must exist to check whether user exist or not ...if that so signup api need to made first

**Comment by sweezy793** [comment]
> @sweezy793 first user must exist to check whether user exist or not ...if that so signup api need to made first

Yes, but isn't that a different thing. The first two issues are regarding the creation of mutation for a temporary post and then we will move on for magic link. I think the signup api creation comes somewhere along the way. Correct me if I'm wrong.

**Comment by abhishek71994** [comment]
conversations on slack/discord please.
