### ISSUE TITLE
Backend : login P1

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#30]
This feature is supposed to help the user(mentor/mentee) to login to the system.

Requirements:

* The request must be of the following type:
    ```
        {
             email:{Inserted email}
             username:{inserted email}
             password:{inserted password}
        }
    ```

* The return should be a *token( preferrably JWT )* along with the username/email(_this for querying_)

**Comment by palashg7563** [comment]
@abhishek71994 i want to take this issue

**Comment by abhishek71994** [comment]
So this particular issue would have sub-issues I will be needing you help with them as well. Can we talk in the slack/discord server and create those issues asap?

**Comment by palashg7563** [comment]
yeah sure

**Comment by palashg7563** [comment]
@abhishek71994 assign me both sign in and singup up api
