### ISSUE TITLE
FrontEnd : Creating a nice landing page

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#31]
Expectations:

* The landing page should have hero text and hero image.(Should have a modern look to it)
* It should have a navbar with relevant links.
* Upon clicking the login/signup button there should be a pop up, with the respective forms.
* footer with links to the social links

**Comment by akshataw** [comment]
I would like to work on this.

**Comment by abhishek71994** [comment]
Okay @akshataw, let's talk in the discord/slack channel for creating more issues for you.

**Comment by palashg7563** [comment]
@abhishek71994 i would also like to work on this

**Comment by abhishek71994** [comment]
@palashg7563 same instructions as I had given to @akshataw.
We have multiple aspects of this issue so there is ample work for anyone, I will create specific issues tailored to the contributor.

**Comment by abhishek71994** [comment]
![image](https://user-images.githubusercontent.com/8072400/59154694-50bb3e80-8aab-11e9-9dd7-26116a7aadf4.png)
Bumping this issue up for grabs.
