### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#34]
Expectations:
* new updated template merging it with the instructions in the old one.

use [this link](https://gist.githubusercontent.com/PurpleBooth/b24679402957c63ec426/raw/5c4f62c1e50c1e6654e76e873aba3df2b0cdeea2/Good-CONTRIBUTING.md-template.md) as a template
Include the current PR style in it.

* Also add an issue creation section which will have the link to [this page](https://embeddedartistry.com/blog/2017/8/18/a-github-issue-template-for-your-projects) to get the issue creation markdown.

**Comment by palashg7563** [comment]
Would love to take this issue @abhishek71994

**Comment by abhishek71994** [comment]
Go for it, fork, change and then PR

**Comment by palashg7563** [comment]
@abhishek71994 can you please close the issue if resolved

**Comment by abhishek71994** [comment]
@palashg7563 can you please update the installation section? now that we have both backend and frontend established?

**Comment by palashg7563** [comment]
Yes Sure @abhishek71994
