### ISSUE TITLE
Backend : Add mentorType to schema

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#37]
# Expected Behavior

The mentorType is to be added to the schema in server-api/schema/index.js

# Current Behavior

MentorType is not added

## Instruction

* setup the following object type:
```
{
    id: ID,
    username: String,
    name: String,
    webinars:[WebinarTypes],
    verified: false/true,
    password : salted,
    bio : String,
    location : String,
    links : {}_public profile links_,
    email : String,
    followers : {menteeTypeID},
    expertise: []_A list of expertise_
}
```

* upon creating that the compilation should show no error and should have no conflicts with the master branch.

**Comment by sweezy793** [comment]
I would like to work on this issue

**Comment by abhishek71994** [comment]
@sweezy793 go ahead
