### ISSUE TITLE
Backend : Add Eslint and mongoose

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#39]
Add eslint, babel and mongoose to the backend API

# Expected Behavior

Add the packages and update the .babelrc file.

# Current Behavior

No babel/mongoose added

**Comment by abhishek71994** [comment]
@palashg7563 #38 has all these features added right?

**Comment by palashg7563** [comment]
@abhishek71994 yes eslint and babel are working fine

**Comment by palashg7563** [comment]
and need to work on eslint rules 😄

**Comment by abhishek71994** [comment]
Good work!
