### ISSUE TITLE
Design the backend system

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#4]
Make all the sketches and the wireframes. Also design the backend.

**Comment by wildcod** [comment]
I want to work on this issue can I work ?

**Comment by wildcod** [comment]
please give Slack link

**Comment by abhishek71994** [comment]
https://discord.gg/FyZjPf
Join the discord channel. We use discord at the moment for communication.

**Comment by wildcod** [comment]
can you please tell me what are the api you want in the backend?
