### ISSUE TITLE
Logo for mentorFix

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#45]
# Expected Behavior

Create a logo for mentor fix

# Current Behavior

There is no logo at the moment

It's expected for the assignee to push the updated resource into the repo after finishing it up

**Comment by akhilmhdh** [comment]
I am interested to work on this issue.

**Comment by imrajat24** [comment]
I would also like to work on this issue

**Comment by abhishek71994** [comment]
Not to make it a competition, let @akhilmhdh work on this at the moment. @imrajat24 let's find another issue for you please.

**Comment by imrajat24** [comment]
@abhishek71994  No problem

**Comment by palashg7563** [comment]
@akhilmhdh have you comeup with something?

**Comment by abhishek71994** [comment]
@imrajat24 referenced and solved this issue in a PR. @akhilmhdh update a PR too if you want it to be merged.

**Comment by palashg7563** [comment]
logo is added in the resource folder so i am closing this issue

**Comment by palashg7563** [comment]
@abhishek71994 can you close this one as issue is already resolved

**Comment by vipuldcoder** [comment]
I am interested with the issue.
