### ISSUE TITLE
Setup the resource/media folder for the project

### ISSUE THREAD

**Issue by imrajat24** [WrippleFoss/mentorFix#46]
# Expected Behavior

The folder should include the hero-image, links to various social media platforms and the logo of the project.

# Current Behavior
There is no resources /media folder present until now.

**Comment by abhishek71994** [comment]
How is  the work going on this?

**Comment by palashg7563** [comment]
for this i have some of the svg ready for the project!

**Comment by abhishek71994** [comment]
@palashg7563 check #50 , is there any resource that you wanna add? If so, ask @imrajat24 to add them in the PR as well.

**Comment by abhishek71994** [comment]
Closing this isssue, #50 merged
