### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#5]
If possible add user auth to the process. Sign in using oauth maybe an option(This is an enhancement).

**Comment by abhishek71994** [comment]
#30 is also dependent on this.

**Comment by eKta37** [comment]
I would like to work on this issue, please assign this task to me.

**Comment by abhishek71994** [comment]
@eKta37 This issue has been tagged obsolete. This won't be a focus for any milestones.
