### ISSUE TITLE
[FRONTEND] Add propTypes to the project

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#53]
# Prerequisites

At the moment, there are no proptypes.

# Expected Behavior

Use react-proptypes to make sure that the valid prop conventions are followed

You can find more info [here](https://reactjs.org/docs/typechecking-with-proptypes.html).

Talk to the mentor/admin before starting this.

**Comment by sweezy793** [comment]
I would like to work on this.

**Comment by abhishek71994** [comment]
Go ahead. Keep note that you may need to update the PR accordingly.
