### ISSUE TITLE
Add a planning docs about Architecture 

### ISSUE THREAD

**Issue by palashgdev** [WrippleFoss/mentorFix#56]
# Prerequisites

# Expected Behavior

Please describe the behavior you are expecting

There is different environments for the projects probably for test production and development 

There is no testing of backend api and for the components 

# Current Behavior

What is the current behavior?

There is no docs for it

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

I will make a Architecture.md for same to resolve the above point mentioning how to resolve it and how to resolve if further issue (if any)

**Comment by palashg7563** [comment]
@abhishek71994 for this docs i will sending the pull request today

**Comment by palashg7563** [comment]
As issue is resolved i am closing this one
