### ISSUE TITLE
[Backend]Create magic link for user

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#64]
# Expected Behavior

When the user signs up, the user shall be asked for
* email
* username

This should be stored in a cached/temporary storage. You have the freedom to decide what you wannna do.

The links that I thought would help are
https://www.npmjs.com/package/passport-magic-link
https://medium.com/@aleksandrasays/sending-magic-links-with-nodejs-765a8686996

# Current Behavior

No feature implemented

**Comment by imrishabh18** [comment]
Hey, i am interested in working on this issue.
