### ISSUE TITLE
Update the template of Issue creation and PR creation

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#71]
![Screen Shot 2019-05-11 at 9 40 32 PM](https://user-images.githubusercontent.com/8072400/57570586-33f10400-7436-11e9-80ad-85315977d754.png)
![Screen Shot 2019-05-11 at 9 40 48 PM](https://user-images.githubusercontent.com/8072400/57570589-39e6e500-7436-11e9-8bef-cf997242a980.png)

Saw these two pop up. Anyone wants to see what the deal is here?

**Comment by vipuldcoder** [comment]
I am interested with the issue.
