### ISSUE TITLE
[FRONT-END]Setup Routes

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#77]
Use Reach Router to setup the following shell component.

`PublicLayout` - does not authenticate user. 
`LoginLayout` - Handles the loggin in and creating session for the user (Form goes here)
`AppLayout`- The protected routes which allow the user to interact.

Use HOC and context to set it up.

**Comment by wildcod** [comment]
I want to take this?

**Comment by abhishek71994** [comment]
Go ahead. You maybe have to create some components. Let me know if you have any questions and I can update you a bit more on the expectations, I'll update that in the issue as well.

Are you in the discord chat?

**Comment by wildcod** [comment]
Yes

**Comment by wildcod** [comment]
Shall I create empty component that you mentioned above?

**Comment by abhishek71994** [comment]
Just open a PR with the changes. I can review it and leave comments which will probably be more helpful than me and you talking about it beforehand.

**Comment by wildcod** [comment]
I saw the App.js file you use react-router there but you told me to use reach-router ?

**Comment by abhishek71994** [comment]
Yeah I would like you to refactor that. It's simpler and can be wrapped around contexts easily.

**Comment by wildcod** [comment]
okay I'll do it
