### ISSUE TITLE
Design basic UI or refer to a template

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#8]
It would be really cool to have a UI or a atleast a basic ui design

**Comment by abhishek71994** [comment]
https://material-ui.com/

We would probably use material design to set up a basic UI.

**Comment by harshil1712** [comment]
I would like to work on this

**Comment by abhishek71994** [comment]
GO for it @harshil1712 I would like to give an idea of the way I hope to take the project before you working on it. So that it works out in that way.

**Comment by hiteshpr** [comment]
I can work on this.

**Comment by harshil1712** [comment]
@abhishek71994 sure, please provide the details.

**Comment by abhishek71994** [comment]
https://join.slack.com/t/wripplefoss/shared_invite/enQtNDQ2OTAzODU4MjI0LTQ0NGY1Mzk5OTI2ZDRkZDE4YzQzZTM4MTBhZWJlZjY2NDcxMmMwNzc0MjRmMzM3NjdiMGVmYTM4ODdkMDMzMTk

Join the slack channel using this link, we can discuss the matter there.
