### ISSUE TITLE
[FRONT-END]Profile page details

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#80]
The profile page will be the same for both mentor and mentee. Gradually we will be branching out.

For now, the following details are

**Public**
```
* Name
* Username
* Expertise (List of labels)
* Certifications if any
* Github 
* Picture(Avatar)
* Followers
* Following
* Connection
```
**If a Connection**
```
* Email
* Linkedin
* Phone number/whatsapp
* Facebook
```

**Comment by wildcod** [comment]
I want to work on this issue but can you describe  how it looks means any sample image that you show me.

**Comment by abhishek71994** [comment]
Hey @wildcod , We are working with a designer to come up with designs. It will be better if you pick up the issue after the designs are finalized. So that you have a path to follow through.

**Comment by eKta37** [comment]
I would like to work on this.
