### ISSUE TITLE
Fix failing tests for CI

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix#91]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Node.js version:
- NPM version
- Operating System:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by wildcod** [comment]
I can take care of this

**Comment by abhishek71994** [comment]
Go for it. Have to write the right unit test.

**Comment by wildcod** [comment]
Okay
